/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;

public class App {

    //na classe App,um banco de dados de autores e um banco de dados de livros

    // private ArrayList<Autor> listaAutores;
    // // private ArrayList<Livro> listaLivros;

    // public App(){
    //     this.listaAutores = new ArrayList<>();
    //     this.listaLivros = new ArrayList<>();
    // }

    // public boolean addAutor(Autor autor){
    //     return this.listaAutores.add(autor)

    // }

    // public boolean addLivro(String isbn, String titulo, Autor[] autores){
    //     ArrayList<Autor> aux = new ArrayList<>(Arrays.asList(autores));
    //     return this.listaLivros.add(new Livro(isbn, titulo, aux));

    // }

    private ArrayList<Motor> motores;
    private Carro carro;

    public static void main(String[] args) {

        Carro carro = new Carro("Volkswagen", new Motor(100, 200));

        System.out.println(carro);

        Motor b = new Motor(150, 300);

        carro.setMotor(b);

        System.out.println(carro);










































































        // App app = new App();

        // app.addAutor(new Autor("Juca", "BRA", LocalDate.of(2000,10,01)));

        // Autor[] authors = {new Autor("Alberto", "BRA", LocalDate.of(2002,02,12))};
        // app.addLivro("1343241234123", "1984", authors);













































        // LocalDate aniv = LocalDate.of(1988, 10, 3);

        // ArrayList<Autor> autores = new ArrayList<>();

        // Autor a = new Autor("Juvineu", "Brasiliano", aniv);
        // Autor b = new Autor("Robert", "Americano", aniv);

        // autores.add(a);
        // autores.add(b);

        // Livro livro = new Livro("asdfbglaewgfjihawe", "em busca do vale encantado", autores);

        // System.out.println(livro);

        // LocalDate aniv2 = LocalDate.of(2000, 5, 25);

        // ArrayList<Autor> autoresB = new ArrayList<>();

        // Autor c = new Autor("Leonardo", "Britanico", aniv2);

        // autoresB.add(c);
        // autoresB.add(a);

        // Livro livro2 = new Livro("quihrunksda", "o senhor dos Paineis", autoresB);

        // System.out.println(livro2);
    }
}
