/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {

    public static void main(String[] args) {
        Pilha<String> A = new Pilha<>(7);
        Pilha<Jogo> B = new Pilha<>(7);

        try {
            A.desempilha();

        }   catch(PilhaLimitesException e) {
            System.out.println("Erro: " + e.getMessage());
        }
    }
}
