/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {

    public static void main(String[] args) {
        Aldeao a = new Aldeao(30, 1, 0.8);
        Personagem p = a;

        a.mover();
        p.mover();

        a.coletarMadeira();
        p.coletarMadeira();
}
