/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {

    public static void main(String[] args) {

        Horario h = new Horario(3,4,5);

        System.out.println(h.toString());

        
    }
}
