/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import org.checkerframework.checker.units.qual.C;

public class App {
    

     public static void main(String[] args) {
    
    //     Carro c = new Carro();

    //     Carro d = new Carro();

    //     System.out.println("velocidade: " + c.obtervelocidade());

    //     c.acelerar(10);

    //     System.out.println("velocidade: " + c.obtervelocidade());


        Contador k = new Contador();

        System.out.println("Valor atual: " + k.obtervalor());

        k.incrementarValor();
        k.incrementarValor();
        k.incrementarValor();
        k.incrementarValor();

        System.out.println("Valor atual: " + k.obtervalor());

        k.atribuirValor(314);


        System.out.println("Valor atual: " + k.obtervalor());


    }
}
