/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

/**
 * Aula de Javadoc
 */

public class App {


    /**
     * Metodo principal
     * @param args argumentos de linha de comando
     */
    public static void main(String[] args) {
    }
}
