/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Scanner;

public class App {
    HashMap<String, Aluno> bancoDeDados = new HashMap<>();
    Scanner teclado = new Scanner(System.in);

    public App(){
        this.bancoDeDados = new HashMap<>();
        this.teclado = new Scanner(System.in);
    }
    
    public void menu(){

        System.out.println("..:: SIGAA ::..");
        System.out.println("1 - Cadastrar");
        System.out.println("2 - Atualizar");
        System.out.println("3 - Remover");
        System.out.println("4 - listar dados de um aluno");
        System.out.println("5 - listar todos os alunos");
        System.out.println("6 - sair");
    }

    public boolean cadastrar(){
        DateTimeFormatter df = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        long matricula = teclado.nextLong();
        int year = teclado.nextInt();
        int mes = teclado.nextInt();
        int dia = teclado.nextInt();
        LocalDate aniv = LocalDate.of(year,mes,dia);
        String nome = this.teclado.nextLine();
        String email = this.teclado.nextLine();
        String curso = this.teclado.nextLine();
        String cpf = this.teclado.nextLine();

        Aluno a = new Aluno(nome, matricula, email, curso, aniv, cpf);
        if(bancoDeDados.containsKey(a.getId())){
            return false;
        } else {
            return true;
        }
    }

    public boolean atualizar(){
        System.out.println("atualizando");
        return false;
    }

    public boolean remover(){
        System.out.println("removendo");
        return false;
    }

    public void dados(){
        System.out.println("listando dados");
    }

    public void listar(){
        this.bancoDeDados.forEach((c,v)->System.out.println(c));
        // System.out.println("listando");
    }

    public static void main(String[] args) {

    

    App app = new App();
    
    
    int opcao = app.teclado.nextInt();

    while(opcao != 6){
        app.menu();
        switch (opcao){
            case 1 -> app.cadastrar();
            case 2 -> app.atualizar();
            case 3 -> app.remover();
            case 4 -> app.dados();
            case 5 -> app.listar();
            }
        opcao = app.teclado.nextInt();
    
    }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        // HashMap <Integer,String> tabela = new HashMap<>();

        // tabela.put(123,"Juca");
        // tabela.put(456,"Ana");

        // String resultado = tabela.get(456);

        // ArrayList<String> lista = new ArrayList<>();

        // lista.add("Juca");
        // lista.add("Ana");
        // lista.add("Pedro");

        // //for i
        // for(int i=0; i < lista.size();i++){
        //     System.out.println(lista.get(i));
        // }

        // //for each

        // for (var e: lista){
        //     System.out.println(e);
        // }

        // lista.forEach(e-> {
        //     System.out.println(e);
        // });

        // tabela.forEach((chave,valor)-> System.out.println(chave + ": " + valor));

        // tabela.remove(123);
    }
}
