/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Scanner;
import java.util.Stack;

public class App {
    

    public static void main(String[] args) {

    //programa que o usuario vai digitar numeros e ser guardado numa colecao
    //se o numero digitado for 999,o programa imprime o número na forma inversa(123 -> 321)


    Scanner teclado = new Scanner(System.in);

    Stack<Integer> colecao = new Stack();
    int numero;
    do{
            numero = teclado.nextInt();
            if(numero != 999){
                colecao.add(numero);
            } else {
                System.out.println("Numeros:");
                while(!colecao.isEmpty()){
                System.out.println(colecao.pop());
                }
            }
        } while(numero != 999);














    //fazer um programa que lerá n numeros que o usuario digitar
    // cada numero devera ser guardado em uma colecao
    // exceto se for 999,se o número digitado for 999,vc deverá imprimir todos os números digitados na tela

    // Scanner teclado = new Scanner(System.in);

    // ArrayList<Integer> colecao = new ArrayList();
    // int numero;
    // do{
    //     numero = teclado.nextInt();
    //     if(numero != 999){
    //         colecao.add(numero);
    //     } else {
    //         System.out.println("Numeros:");
    //         colecao.forEach(System.out::println);
    //     }
    // } while(numero != 999);




















   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
    //     ArrayList<String> contatos = new ArrayList();

    //     contatos.add("Juca");
    //     contatos.add("Ana");
    //     contatos.add("Pedro");


    //     contatos.forEach(System.out::println);


    //     Collections.sort(contatos);

    //     contatos.forEach(System.out::println);

    //     Collections.shuffle(contatos);

    //     contatos.forEach(System.out::println);






































































































        // for(int i=0; i < contatos.size();i++){
        //     System.out.println("Nome: " + contatos.get(i));
        // }

        // for (var nome : contatos) {
        //     System.out.println("Nome: " + nome);
        // }

        // contatos.forEach(elemento -> System.out.println("nome: " + elemento));


        // int pos = contatos.indexOf("Ana");
        // if (pos>=0){
        //     contatos.remove(pos);
        // }

        // System.out.println(contatos + ", " + contatos.size() + ", " + contatos.indexOf("Pedro"));

        // contatos.add("Ana");

        // System.out.println(contatos);

        // contatos.removeIf(e->e.equals("Ana"));

        // System.out.println(contatos + ", " + contatos.size() + ", " + contatos.indexOf("Pedro"));



























































        // contatos.remove(pos);

        // System.out.println(contatos + ", " + contatos.size() + ", " + contatos.indexOf("Pedro"));

        // contatos.remove("Ana");

        // System.out.println(contatos + ", " + contatos.size() + ", " + contatos.indexOf("Pedro"));








































        // ArrayList<String> outro = new ArrayList();

        // outro.add("Juca");
        // outro.add("Ana");
        // outro.add("Pedro");

        // ArrayList<String> nova;

        // nova = (ArrayList<String>) outro.clone();



















        // String resultado = contatos.get(1);

        // System.out.println(resultado);

        // if(contatos.contains("Ana")){
        //     System.out.println("Ana é um contato");
        // }














        // System.out.println("Total de contatos: " + contatos.size());

        // contatos.add("Joao");

        // System.out.println("Total de contatos: " + contatos.size());


    }
}
