/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class Ex03 {


    public static void main(String[] args) {
        Retangulo ret = new Retangulo();

        System.out.println(ret);

        Retangulo ret2 = new Retangulo("UTF8");

        System.out.println(ret2);

        ret.setAltura(7);
        ret.setLargura(12);

        ret2.setAltura(14);
        ret2.setLargura(8);

        System.out.println(ret);
        System.out.println(ret2);
    }
}
