/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.time.LocalDate;
import java.util.HashMap;
import java.util.Scanner;
import java.util.ArrayList;

public class App {

    private Scanner teclado = new Scanner(System.in);
    private Agenda agenda;

    public App(){
        this.teclado = new Scanner(System.in);
        this.agenda = new Agenda();

    }

    public void menu(){
        System.out.println("..:AGENDA DIGITAL:..");
        System.out.println("1->Adicionar Contato");
        System.out.println("2->Atualizar Contato");
        System.out.println("3->Remover Contato");
        System.out.println("4->Mostrar dados de um Contato");
        System.out.println("5->Mostrar dados de todos os contatos");
        System.out.println("6->Sair");
    }

    public void mostraDados(){
        System.out.println("Qual o nome do contato?");
        String n = this.teclado.nextLine();
        ArrayList<Contato> nomes = new ArrayList<>();
        Contato c;
        agenda.getContatos().forEach(e -> {
            if(e.getNome().equals(n)){
                nomes.add(n);
            }
        });
        if (nomes.size() > 1) {
            System.out.println("qual o sobrenome");
            String s = this.teclado.nextLine();
            nomes.forEach(e-> {
                if(e.getSobrenome().equals(s)){
                    c = e;
                }
            });
        } else {
            c = nomes.get(0);
        }
        System.out.println(c);


    }

    public void todosOsDados(){
        System.out.println(this.agenda);
    }

    public static void main(String[] args) {

        App app = new App();

        int opcao = app.teclado.nextInt();

        while(opcao!=6){
            app.menu();
            switch(opcao){
                case1->app.addContato();
                case2->app.updateContato();
                case3->app.removeContato();
                case4->app.mostraDados();
                case5->app.todosOsDados();
            }
            opcao = app.teclado.nextInt();
        }



        
    }
}















































// LocalDate d = LocalDate.of(2000, 12, 02);
        // Telefone i = new Telefone("48997104826");
        // Telefone j = new Telefone("48997104384");
        // Telefone k = new Telefone("48923604826");

        // Email l = new Email("abc@gmail.com");
        // Email m = new Email("jkl@ifsc.edu.br");

        // HashMap<String,Telefone> lista1 = new HashMap<>();
        // lista1.put("ab", i);
        // lista1.put("jk", j);
        // lista1.put("lm",k);

        // HashMap<String,Email> lista2 = new HashMap<>();

        // lista2.put("ab",l);
        // lista2.put("jk",m);
        // Contato c = new Contato("Joao", "Miranda",d , lista1, lista2);

        // System.out.println(c);